select * from public.customer_shopping_behavior

--Q1. What is the total revenue generated by male vs female customers ?
select gender,sum(purchase_amount) as revenue from public.customer_shopping_behavior
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount ?
select customer_id,purchase_amount from public.customer_shopping_behavior
where discount_applied like 'Yes' 
and purchase_amount >= (select avg(purchase_amount) from public.customer_shopping_behavior)

--Q3. What are the top 5 products with the highest average review rating ?
select  item_purchased, ROUND(avg(review_rating::numeric),2) as "Average Product Rating"  from public.customer_shopping_behavior 
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping
select shipping_type, round(avg(purchase_amount),2) as "Average Purchase Amount" from public.customer_shopping_behavior
group by shipping_type
having shipping_type in('Standard','Express')

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
round(avg(purchase_amount),2) as "Average Spend Amount",
sum(purchase_amount) as "Total Revenue"
from public.customer_shopping_behavior
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select  item_purchased, round(100 * sum(case when discount_applied like 'Yes' then 1 else 0 end)/count(*),2) as "discount_rate"  from public.customer_shopping_behavior
group by item_purchased 
order by discount_rate desc
limit 5

--Q7. Segment customers into New (1 purchase), Returning (between 2 and 10),
--and Loyal (more than 10) based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select 
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal' 
	end as customer_segment
from public.customer_shopping_behavior
)


select customer_segment, count (*) as "Number of Customers" from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?
with items_purchased as (
select category,
item_purchased,
sum(purchase_amount) as "Total Purchases",
ROW_NUMBER() OVER(partition by category order by sum(purchase_amount) desc) as item_rank
from public.customer_shopping_behavior
group by category, item_purchased
)

select * from items_purchased where item_rank <= 3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from public.customer_shopping_behavior
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as "Total Purchases"
from public.customer_shopping_behavior
group by age_group
order by sum(purchase_amount) desc